name: project1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip=23.3.1
  - pinocchio=3.0.0
  - python-orocos-kdl=1.5.1
  - ipdb
  - pip:
      - casadi==3.6.5
      - einops==0.7.0
      - kornia==0.7.3
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.6
      - torch==2.0.1
      - -e .
